# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cd73a5b9dcd9a1fffde724344500f9769f70fc0c1b77aa27871b799cac3c22f05025194caa47171588a0ddb6dba3b597716f79cf795b5728cf162a6130a42d0

test:
  secret_key_base: 9fa2ccc8f862a34c19f2388476efaa4960b8d330f84bbd7fedc5a6cc574385d1f99f6a5d8cd0c535aeba90cfa40adcaaefa7c9d3328d914323d379dc7df1dc28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
